### ISSUE TITLE
Deprecated/obsoleted by wpcmrf?

### ISSUE THREAD

**Issue by JoeMurray** [CiviMRF/cmrf-wordpress#1]
I haven't used CiviMRF and am considering it for a WP project and am trying to make sense of the variety of inter-related extensions. Is this one still needed, if it hasn't seen an update since 2019 and wpcmrf is getting patches more regularly? If both are needed, what is the relationship between them?

**Comment by bjendres** [comment]
Hi Joe. I think it might be, this here is an approach to a CMRF Wordpress implementation that originated in the Amsterdam sprint. As you can see it wasn't really pushed forward since then, and it is my no means functional (afaik). So, yes, it's most likely that Jaap's wpcmrf will take over.

**Comment by JoeMurray** [comment]
Thanks!
